# Generated by Django 4.2.6 on 2023-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamento', '0002_agendamento_clinica'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='atendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='faltou',
            field=models.BooleanField(default=False),
        ),
    ]
