# Generated by Django 4.2.6 on 2023-12-04 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('idMedico', models.AutoField(primary_key=True, serialize=False)),
                ('crm', models.CharField(max_length=6)),
                ('senha', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=16)),
                ('nomeCompleto', models.CharField(max_length=255)),
                ('foto', models.ImageField(upload_to='fotos/medicos')),
            ],
        ),
    ]
