version: '3.8'

services:

  app:
    build: .
    container_name: api-cardiotech
    restart: always
    tty: true


    ports:
      - 8000:8000
    
    volumes:
      - .:/api_cardiotech
    
    command: python manage.py runserver 0.0.0.0:8000
  
  django:
    container_name: django
    image: django
